// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: approved-users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApprovedUser = `-- name: CreateApprovedUser :one
INSERT INTO approved_users (email, first_name, created_by)
VALUES ($1, $2, $3)
RETURNING id, email, first_name, created_by, created_at, updated_at
`

type CreateApprovedUserParams struct {
	Email     string      `json:"email"`
	FirstName string      `json:"first_name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateApprovedUser(ctx context.Context, arg CreateApprovedUserParams) (ApprovedUser, error) {
	row := q.db.QueryRow(ctx, createApprovedUser, arg.Email, arg.FirstName, arg.CreatedBy)
	var i ApprovedUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createApprovedUsersBulk = `-- name: CreateApprovedUsersBulk :many
INSERT INTO approved_users (email, first_name, created_by)
SELECT unnest($1::TEXT[]) AS email,
       unnest($2::TEXT[]) AS first_name,
       unnest($3::UUID[]) AS created_by
RETURNING id, email, first_name, created_by, created_at, updated_at
`

type CreateApprovedUsersBulkParams struct {
	Column1 []string      `json:"column_1"`
	Column2 []string      `json:"column_2"`
	Column3 []pgtype.UUID `json:"column_3"`
}

func (q *Queries) CreateApprovedUsersBulk(ctx context.Context, arg CreateApprovedUsersBulkParams) ([]ApprovedUser, error) {
	rows, err := q.db.Query(ctx, createApprovedUsersBulk, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovedUser
	for rows.Next() {
		var i ApprovedUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteApprovedUser = `-- name: DeleteApprovedUser :execrows
DELETE FROM approved_users
WHERE id = $1
`

func (q *Queries) DeleteApprovedUser(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteApprovedUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getApprovedUserByEmail = `-- name: GetApprovedUserByEmail :one
SELECT id, email, first_name, created_by, created_at, updated_at
FROM approved_users
WHERE email = $1
`

func (q *Queries) GetApprovedUserByEmail(ctx context.Context, email string) (ApprovedUser, error) {
	row := q.db.QueryRow(ctx, getApprovedUserByEmail, email)
	var i ApprovedUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApprovedUserByID = `-- name: GetApprovedUserByID :one
SELECT id, email, first_name, created_by, created_at, updated_at
FROM approved_users
WHERE id = $1
`

func (q *Queries) GetApprovedUserByID(ctx context.Context, id pgtype.UUID) (ApprovedUser, error) {
	row := q.db.QueryRow(ctx, getApprovedUserByID, id)
	var i ApprovedUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApprovedUsers = `-- name: ListApprovedUsers :many
SELECT id, email, first_name, created_by, created_at, updated_at
FROM approved_users
ORDER BY created_at DESC
`

func (q *Queries) ListApprovedUsers(ctx context.Context) ([]ApprovedUser, error) {
	rows, err := q.db.Query(ctx, listApprovedUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApprovedUser
	for rows.Next() {
		var i ApprovedUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
