// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approvedUserExists = `-- name: ApprovedUserExists :one
SELECT EXISTS(SELECT 1 FROM approved_users WHERE id = $1)
`

func (q *Queries) ApprovedUserExists(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, approvedUserExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const assignRole = `-- name: AssignRole :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT (user_id, role_id) DO NOTHING
`

type AssignRoleParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignRole(ctx context.Context, arg AssignRoleParams) error {
	_, err := q.db.Exec(ctx, assignRole, arg.UserID, arg.RoleID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (approved_user_id, email, password_hash, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, approved_user_id, email, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	ApprovedUserID pgtype.UUID `json:"approved_user_id"`
	Email          string      `json:"email"`
	PasswordHash   string      `json:"password_hash"`
	IsActive       bool        `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ApprovedUserID,
		arg.Email,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ApprovedUserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at
FROM roles
WHERE name = $1
LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getRolesByNames = `-- name: GetRolesByNames :many
SELECT id, name, description, created_at
FROM roles
WHERE name = ANY($1::TEXT[])
`

func (q *Queries) GetRolesByNames(ctx context.Context, dollar_1 []string) ([]Role, error) {
	rows, err := q.db.Query(ctx, getRolesByNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, approved_user_id, email, password_hash, is_active, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ApprovedUserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, approved_user_id, email, password_hash, is_active, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ApprovedUserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.id, r.name, r.description, r.created_at
FROM roles r
INNER JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetUserRoles(ctx context.Context, userID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, getUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserWithRolesAndApproved = `-- name: GetUserWithRolesAndApproved :one
SELECT
    u.id, u.approved_user_id, u.email, u.password_hash, u.is_active, u.created_at, u.updated_at,
    COALESCE(
        (SELECT array_agg(r.name ORDER BY r.name)
         FROM user_roles ur JOIN roles r ON r.id = ur.role_id
         WHERE ur.user_id = u.id),
        ARRAY[]::text[]
    ) AS role_names,
    a.id          AS approved_id,
    a.email       AS approved_email,
    a.first_name  AS approved_first_name,
    a.created_by  AS approved_created_by,
    a.created_at  AS approved_created_at,
    a.updated_at  AS approved_updated_at
FROM users u
LEFT JOIN approved_users a ON a.id = u.approved_user_id
WHERE u.id = $1
`

type GetUserWithRolesAndApprovedRow struct {
	ID                pgtype.UUID        `json:"id"`
	ApprovedUserID    pgtype.UUID        `json:"approved_user_id"`
	Email             string             `json:"email"`
	PasswordHash      string             `json:"password_hash"`
	IsActive          bool               `json:"is_active"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	RoleNames         interface{}        `json:"role_names"`
	ApprovedID        pgtype.UUID        `json:"approved_id"`
	ApprovedEmail     *string            `json:"approved_email"`
	ApprovedFirstName *string            `json:"approved_first_name"`
	ApprovedCreatedBy pgtype.UUID        `json:"approved_created_by"`
	ApprovedCreatedAt pgtype.Timestamptz `json:"approved_created_at"`
	ApprovedUpdatedAt pgtype.Timestamptz `json:"approved_updated_at"`
}

// Single-query aggregate used by the auth middleware on every request.
// Returns the user row, a text[] of role names, and the joined approved_user
// (NULL when the user has no approved_user link). Three roundtrips in one.
func (q *Queries) GetUserWithRolesAndApproved(ctx context.Context, id pgtype.UUID) (GetUserWithRolesAndApprovedRow, error) {
	row := q.db.QueryRow(ctx, getUserWithRolesAndApproved, id)
	var i GetUserWithRolesAndApprovedRow
	err := row.Scan(
		&i.ID,
		&i.ApprovedUserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleNames,
		&i.ApprovedID,
		&i.ApprovedEmail,
		&i.ApprovedFirstName,
		&i.ApprovedCreatedBy,
		&i.ApprovedCreatedAt,
		&i.ApprovedUpdatedAt,
	)
	return i, err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $2, password_hash = $3, is_active = $4, updated_at = NOW()
WHERE id = $1
RETURNING id, approved_user_id, email, password_hash, is_active, created_at, updated_at
`

type UpdateUserParams struct {
	ID           pgtype.UUID `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	IsActive     bool        `json:"is_active"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ApprovedUserID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
