// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todo.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (user_id, title, description, is_completed, due_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, title, description, is_completed, due_date, created_at, updated_at
`

type CreateTodoParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	IsCompleted bool               `json:"is_completed"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.IsCompleted,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos
WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodo, id)
	return err
}

const deleteTodosByUserID = `-- name: DeleteTodosByUserID :exec
DELETE FROM todos
WHERE user_id = $1
`

func (q *Queries) DeleteTodosByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTodosByUserID, userID)
	return err
}

const getTodoByID = `-- name: GetTodoByID :one
SELECT id, user_id, title, description, is_completed, due_date, created_at, updated_at
FROM todos
WHERE id = $1
`

func (q *Queries) GetTodoByID(ctx context.Context, id pgtype.UUID) (Todo, error) {
	row := q.db.QueryRow(ctx, getTodoByID, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTodosByUserID = `-- name: ListTodosByUserID :many
SELECT id, user_id, title, description, is_completed, due_date, created_at, updated_at
FROM todos
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTodosByUserID(ctx context.Context, userID pgtype.UUID) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByUserIDWithFilters = `-- name: ListTodosByUserIDWithFilters :many
SELECT id, user_id, title, description, is_completed, due_date, created_at, updated_at
FROM todos
WHERE user_id = $1
    AND ($2::BOOLEAN IS NULL OR is_completed = $2::BOOLEAN)
ORDER BY
    CASE WHEN $3 = 'due_date' THEN due_date END,
    CASE WHEN $3 = 'created_at' THEN created_at END,
    CASE WHEN $3 = 'title' THEN title END
DESC NULLS LAST
`

type ListTodosByUserIDWithFiltersParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	IsCompleted *bool       `json:"is_completed"`
	SortBy      interface{} `json:"sort_by"`
}

func (q *Queries) ListTodosByUserIDWithFilters(ctx context.Context, arg ListTodosByUserIDWithFiltersParams) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodosByUserIDWithFilters, arg.UserID, arg.IsCompleted, arg.SortBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsCompleted,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos
SET title = $2, description = $3, is_completed = $4, due_date = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, description, is_completed, due_date, created_at, updated_at
`

type UpdateTodoParams struct {
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	IsCompleted bool               `json:"is_completed"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodo,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.IsCompleted,
		arg.DueDate,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTodoPartial = `-- name: UpdateTodoPartial :one
UPDATE todos
SET
    title        = COALESCE($1::TEXT,         title),
    description  = COALESCE($2::TEXT,   description),
    is_completed = COALESCE($3::BOOLEAN, is_completed),
    due_date     = COALESCE($4::TIMESTAMPTZ, due_date),
    updated_at   = NOW()
WHERE id = $5
RETURNING id, user_id, title, description, is_completed, due_date, created_at, updated_at
`

type UpdateTodoPartialParams struct {
	Title       *string            `json:"title"`
	Description *string            `json:"description"`
	IsCompleted *bool              `json:"is_completed"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ID          pgtype.UUID        `json:"id"`
}

// PATCH-style update. Any nil named arg preserves the existing column.
// The service layer is responsible for converting empty strings to nil.
func (q *Queries) UpdateTodoPartial(ctx context.Context, arg UpdateTodoPartialParams) (Todo, error) {
	row := q.db.QueryRow(ctx, updateTodoPartial,
		arg.Title,
		arg.Description,
		arg.IsCompleted,
		arg.DueDate,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
