// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ApprovedUserRequest defines model for ApprovedUserRequest.
type ApprovedUserRequest struct {
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
}

// ApprovedUserResponse defines model for ApprovedUserResponse.
type ApprovedUserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	Id        string    `json:"id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token     string `json:"token"`
	TokenType string `json:"token_type"`
}

// BulkApprovedUserRequest defines model for BulkApprovedUserRequest.
type BulkApprovedUserRequest struct {
	Users []ApprovedUserRequest `json:"users"`
}

// CreateTodoRequest defines model for CreateTodoRequest.
type CreateTodoRequest struct {
	Description *string    `json:"description"`
	DueDate     *time.Time `json:"due_date"`
	Title       string     `json:"title"`
}

// Error defines model for Error.
type Error struct {
	Detail string `json:"detail"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	ApprovedId string              `json:"approved_id"`
	Email      openapi_types.Email `json:"email"`
	Password   string              `json:"password"`
}

// TodoResponse defines model for TodoResponse.
type TodoResponse struct {
	CreatedAt   time.Time  `json:"created_at"`
	Description *string    `json:"description"`
	DueDate     *time.Time `json:"due_date"`
	Id          string     `json:"id"`
	IsCompleted bool       `json:"is_completed"`
	Title       string     `json:"title"`
	UpdatedAt   time.Time  `json:"updated_at"`
	UserId      string     `json:"user_id"`
}

// UpdateTodoRequest defines model for UpdateTodoRequest.
type UpdateTodoRequest struct {
	Description *string    `json:"description"`
	DueDate     *time.Time `json:"due_date"`
	IsCompleted *bool      `json:"is_completed"`
	Title       *string    `json:"title"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	FirstName string    `json:"first_name"`
	Id        string    `json:"id"`
	IsActive  bool      `json:"is_active"`
	Roles     []string  `json:"roles"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// CreateApprovedUserJSONRequestBody defines body for CreateApprovedUser for application/json ContentType.
type CreateApprovedUserJSONRequestBody = ApprovedUserRequest

// BulkCreateApprovedUsersJSONRequestBody defines body for BulkCreateApprovedUsers for application/json ContentType.
type BulkCreateApprovedUsersJSONRequestBody = BulkApprovedUserRequest

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = CreateTodoRequest

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodoRequest
